M48
; DRILL file {KiCad 9.0.2} date 2026-04-16T01:13:01+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-16T01:13:01+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X181.706Y-97.282
T2
X168.664Y-65.427
X168.664Y-113.427
X176.61Y-65.427
X176.61Y-113.427
M30
